/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as TestResponseRouteImport } from './routes/test/response'
import { Route as TestEditRouteImport } from './routes/test/edit'
import { Route as TestCreateRouteImport } from './routes/test/create'
import { Route as FIdRouteImport } from './routes/f/$id'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ProtectedResponsesIndexRouteImport } from './routes/_protected/responses/index'
import { Route as ProtectedFormsIndexRouteImport } from './routes/_protected/forms/index'
import { Route as ProtectedFormsCreateRouteImport } from './routes/_protected/forms/create'
import { Route as ProtectedFormsIdIndexRouteImport } from './routes/_protected/forms/$id/index'
import { Route as ProtectedFormsIdResponsesRouteImport } from './routes/_protected/forms/$id/responses'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResponseRoute = TestResponseRouteImport.update({
  id: '/test/response',
  path: '/test/response',
  getParentRoute: () => rootRouteImport,
} as any)
const TestEditRoute = TestEditRouteImport.update({
  id: '/test/edit',
  path: '/test/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCreateRoute = TestCreateRouteImport.update({
  id: '/test/create',
  path: '/test/create',
  getParentRoute: () => rootRouteImport,
} as any)
const FIdRoute = FIdRouteImport.update({
  id: '/f/$id',
  path: '/f/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedResponsesIndexRoute = ProtectedResponsesIndexRouteImport.update({
  id: '/responses/',
  path: '/responses/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFormsIndexRoute = ProtectedFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFormsCreateRoute = ProtectedFormsCreateRouteImport.update({
  id: '/forms/create',
  path: '/forms/create',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFormsIdIndexRoute = ProtectedFormsIdIndexRouteImport.update({
  id: '/forms/$id/',
  path: '/forms/$id/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFormsIdResponsesRoute =
  ProtectedFormsIdResponsesRouteImport.update({
    id: '/forms/$id/responses',
    path: '/forms/$id/responses',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/f/$id': typeof FIdRoute
  '/test/create': typeof TestCreateRoute
  '/test/edit': typeof TestEditRoute
  '/test/response': typeof TestResponseRoute
  '/test/': typeof TestIndexRoute
  '/forms/create': typeof ProtectedFormsCreateRoute
  '/forms/': typeof ProtectedFormsIndexRoute
  '/responses/': typeof ProtectedResponsesIndexRoute
  '/forms/$id/responses': typeof ProtectedFormsIdResponsesRoute
  '/forms/$id/': typeof ProtectedFormsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/f/$id': typeof FIdRoute
  '/test/create': typeof TestCreateRoute
  '/test/edit': typeof TestEditRoute
  '/test/response': typeof TestResponseRoute
  '/test': typeof TestIndexRoute
  '/forms/create': typeof ProtectedFormsCreateRoute
  '/forms': typeof ProtectedFormsIndexRoute
  '/responses': typeof ProtectedResponsesIndexRoute
  '/forms/$id/responses': typeof ProtectedFormsIdResponsesRoute
  '/forms/$id': typeof ProtectedFormsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/f/$id': typeof FIdRoute
  '/test/create': typeof TestCreateRoute
  '/test/edit': typeof TestEditRoute
  '/test/response': typeof TestResponseRoute
  '/test/': typeof TestIndexRoute
  '/_protected/forms/create': typeof ProtectedFormsCreateRoute
  '/_protected/forms/': typeof ProtectedFormsIndexRoute
  '/_protected/responses/': typeof ProtectedResponsesIndexRoute
  '/_protected/forms/$id/responses': typeof ProtectedFormsIdResponsesRoute
  '/_protected/forms/$id/': typeof ProtectedFormsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/f/$id'
    | '/test/create'
    | '/test/edit'
    | '/test/response'
    | '/test/'
    | '/forms/create'
    | '/forms/'
    | '/responses/'
    | '/forms/$id/responses'
    | '/forms/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/f/$id'
    | '/test/create'
    | '/test/edit'
    | '/test/response'
    | '/test'
    | '/forms/create'
    | '/forms'
    | '/responses'
    | '/forms/$id/responses'
    | '/forms/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth/sign-in'
    | '/f/$id'
    | '/test/create'
    | '/test/edit'
    | '/test/response'
    | '/test/'
    | '/_protected/forms/create'
    | '/_protected/forms/'
    | '/_protected/responses/'
    | '/_protected/forms/$id/responses'
    | '/_protected/forms/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  FIdRoute: typeof FIdRoute
  TestCreateRoute: typeof TestCreateRoute
  TestEditRoute: typeof TestEditRoute
  TestResponseRoute: typeof TestResponseRoute
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/response': {
      id: '/test/response'
      path: '/test/response'
      fullPath: '/test/response'
      preLoaderRoute: typeof TestResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/edit': {
      id: '/test/edit'
      path: '/test/edit'
      fullPath: '/test/edit'
      preLoaderRoute: typeof TestEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/create': {
      id: '/test/create'
      path: '/test/create'
      fullPath: '/test/create'
      preLoaderRoute: typeof TestCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$id': {
      id: '/f/$id'
      path: '/f/$id'
      fullPath: '/f/$id'
      preLoaderRoute: typeof FIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/responses/': {
      id: '/_protected/responses/'
      path: '/responses'
      fullPath: '/responses/'
      preLoaderRoute: typeof ProtectedResponsesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forms/': {
      id: '/_protected/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof ProtectedFormsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forms/create': {
      id: '/_protected/forms/create'
      path: '/forms/create'
      fullPath: '/forms/create'
      preLoaderRoute: typeof ProtectedFormsCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forms/$id/': {
      id: '/_protected/forms/$id/'
      path: '/forms/$id'
      fullPath: '/forms/$id/'
      preLoaderRoute: typeof ProtectedFormsIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forms/$id/responses': {
      id: '/_protected/forms/$id/responses'
      path: '/forms/$id/responses'
      fullPath: '/forms/$id/responses'
      preLoaderRoute: typeof ProtectedFormsIdResponsesRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedFormsCreateRoute: typeof ProtectedFormsCreateRoute
  ProtectedFormsIndexRoute: typeof ProtectedFormsIndexRoute
  ProtectedResponsesIndexRoute: typeof ProtectedResponsesIndexRoute
  ProtectedFormsIdResponsesRoute: typeof ProtectedFormsIdResponsesRoute
  ProtectedFormsIdIndexRoute: typeof ProtectedFormsIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedFormsCreateRoute: ProtectedFormsCreateRoute,
  ProtectedFormsIndexRoute: ProtectedFormsIndexRoute,
  ProtectedResponsesIndexRoute: ProtectedResponsesIndexRoute,
  ProtectedFormsIdResponsesRoute: ProtectedFormsIdResponsesRoute,
  ProtectedFormsIdIndexRoute: ProtectedFormsIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  FIdRoute: FIdRoute,
  TestCreateRoute: TestCreateRoute,
  TestEditRoute: TestEditRoute,
  TestResponseRoute: TestResponseRoute,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
