/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FIdRouteImport } from './routes/f/$id'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ProtectedFormsIndexRouteImport } from './routes/_protected/forms/index'
import { Route as ProtectedFormsCreateRouteImport } from './routes/_protected/forms/create'
import { Route as ProtectedFormsIdIndexRouteImport } from './routes/_protected/forms/$id/index'
import { Route as ProtectedFormsIdResponsesIndexRouteImport } from './routes/_protected/forms/$id/responses/index'
import { Route as ProtectedFormsIdResponsesSubmissionIdRouteImport } from './routes/_protected/forms/$id/responses/$submissionId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FIdRoute = FIdRouteImport.update({
  id: '/f/$id',
  path: '/f/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedFormsIndexRoute = ProtectedFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFormsCreateRoute = ProtectedFormsCreateRouteImport.update({
  id: '/forms/create',
  path: '/forms/create',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFormsIdIndexRoute = ProtectedFormsIdIndexRouteImport.update({
  id: '/forms/$id/',
  path: '/forms/$id/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFormsIdResponsesIndexRoute =
  ProtectedFormsIdResponsesIndexRouteImport.update({
    id: '/forms/$id/responses/',
    path: '/forms/$id/responses/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedFormsIdResponsesSubmissionIdRoute =
  ProtectedFormsIdResponsesSubmissionIdRouteImport.update({
    id: '/forms/$id/responses/$submissionId',
    path: '/forms/$id/responses/$submissionId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/f/$id': typeof FIdRoute
  '/forms/create': typeof ProtectedFormsCreateRoute
  '/forms/': typeof ProtectedFormsIndexRoute
  '/forms/$id/': typeof ProtectedFormsIdIndexRoute
  '/forms/$id/responses/$submissionId': typeof ProtectedFormsIdResponsesSubmissionIdRoute
  '/forms/$id/responses/': typeof ProtectedFormsIdResponsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/f/$id': typeof FIdRoute
  '/forms/create': typeof ProtectedFormsCreateRoute
  '/forms': typeof ProtectedFormsIndexRoute
  '/forms/$id': typeof ProtectedFormsIdIndexRoute
  '/forms/$id/responses/$submissionId': typeof ProtectedFormsIdResponsesSubmissionIdRoute
  '/forms/$id/responses': typeof ProtectedFormsIdResponsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/f/$id': typeof FIdRoute
  '/_protected/forms/create': typeof ProtectedFormsCreateRoute
  '/_protected/forms/': typeof ProtectedFormsIndexRoute
  '/_protected/forms/$id/': typeof ProtectedFormsIdIndexRoute
  '/_protected/forms/$id/responses/$submissionId': typeof ProtectedFormsIdResponsesSubmissionIdRoute
  '/_protected/forms/$id/responses/': typeof ProtectedFormsIdResponsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/f/$id'
    | '/forms/create'
    | '/forms/'
    | '/forms/$id/'
    | '/forms/$id/responses/$submissionId'
    | '/forms/$id/responses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/f/$id'
    | '/forms/create'
    | '/forms'
    | '/forms/$id'
    | '/forms/$id/responses/$submissionId'
    | '/forms/$id/responses'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth/sign-in'
    | '/f/$id'
    | '/_protected/forms/create'
    | '/_protected/forms/'
    | '/_protected/forms/$id/'
    | '/_protected/forms/$id/responses/$submissionId'
    | '/_protected/forms/$id/responses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  FIdRoute: typeof FIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$id': {
      id: '/f/$id'
      path: '/f/$id'
      fullPath: '/f/$id'
      preLoaderRoute: typeof FIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/forms/': {
      id: '/_protected/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof ProtectedFormsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forms/create': {
      id: '/_protected/forms/create'
      path: '/forms/create'
      fullPath: '/forms/create'
      preLoaderRoute: typeof ProtectedFormsCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forms/$id/': {
      id: '/_protected/forms/$id/'
      path: '/forms/$id'
      fullPath: '/forms/$id/'
      preLoaderRoute: typeof ProtectedFormsIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forms/$id/responses/': {
      id: '/_protected/forms/$id/responses/'
      path: '/forms/$id/responses'
      fullPath: '/forms/$id/responses/'
      preLoaderRoute: typeof ProtectedFormsIdResponsesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forms/$id/responses/$submissionId': {
      id: '/_protected/forms/$id/responses/$submissionId'
      path: '/forms/$id/responses/$submissionId'
      fullPath: '/forms/$id/responses/$submissionId'
      preLoaderRoute: typeof ProtectedFormsIdResponsesSubmissionIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedFormsCreateRoute: typeof ProtectedFormsCreateRoute
  ProtectedFormsIndexRoute: typeof ProtectedFormsIndexRoute
  ProtectedFormsIdIndexRoute: typeof ProtectedFormsIdIndexRoute
  ProtectedFormsIdResponsesSubmissionIdRoute: typeof ProtectedFormsIdResponsesSubmissionIdRoute
  ProtectedFormsIdResponsesIndexRoute: typeof ProtectedFormsIdResponsesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedFormsCreateRoute: ProtectedFormsCreateRoute,
  ProtectedFormsIndexRoute: ProtectedFormsIndexRoute,
  ProtectedFormsIdIndexRoute: ProtectedFormsIdIndexRoute,
  ProtectedFormsIdResponsesSubmissionIdRoute:
    ProtectedFormsIdResponsesSubmissionIdRoute,
  ProtectedFormsIdResponsesIndexRoute: ProtectedFormsIdResponsesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  FIdRoute: FIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
