name: Build Container, Push to Registry, and Deploy to EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_deploy:
    name: Build , push to GHCR and deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
        with:
          cosign-release: "v2.1.1"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./dynamic-form-builder
          file: ./dynamic-form-builder/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-client:latest

      # =========================

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./dynamic-form-builder-engine
          file: ./dynamic-form-builder-engine/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest

      - name: Debug OIDC claims
        run: |
          echo "repository: ${{ github.repository }}"
          echo "repository_owner: ${{ github.repository_owner }}"
          echo "ref: ${{ github.ref }}"
          echo "role ARN being assumed: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role_Personal"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: af-south-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role_Personal

      #      - name: Deploy to EC2
      #        run: |
      #          # Extract first tag from metadata JSON
      #          IMAGE_TAG=$(echo '${{ steps.meta.outputs.json }}' | jq -r '.tags[0]')
      #          echo "Deploying image: $IMAGE_TAG"
      #
      #          COMMAND_ID=$(aws ssm send-command \
      #            --instance-ids ${{secrets.EC2_INSTANCE_ID}} \
      #            --document-name "AWS-RunShellScript" \
      #            --parameters 'commands=[
      #              "cd /opt/staging/api",
      #              "echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin",
      #              "docker pull '"$IMAGE_TAG"'",
      #              "docker compose pull",
      #              "docker compose up -d --force-recreate",
      #              "docker compose ps",
      #              "docker system prune -af",
      #              "docker compose logs --tail 30 vyte-api"
      #            ]' \
      #            --region af-south-1 \
      #            --output text \
      #            --query "Command.CommandId")
      #
      #          echo "Command ID: $COMMAND_ID"
      #          sleep 15
      #
      #          aws ssm get-command-invocation \
      #            --command-id $COMMAND_ID \
      #            --instance-id ${{secrets.EC2_INSTANCE_ID}} \
      #            --region af-south-1 \
      #            --query "StandardOutputContent" \
      #            --output text

      - name: Get caller identity
        run: |
          echo "✅ Successfully authenticated as:"
          aws sts get-caller-identity

      - name: List files in /opt directory
        run: |
          echo "📂 Sending command to EC2..."

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{secrets.EC2_INSTANCE_ID}} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["ls -lah /opt"]' \
            --region af-south-1 \
            --output text \
            --query "Command.CommandId")

          echo "Command ID: $COMMAND_ID"
          sleep 10


          aws ssm get-command-invocation \
            --command-id $COMMAND_ID \
            --instance-id ${{secrets.EC2_INSTANCE_ID}} \
            --region af-south-1 \
            --query "StandardOutputContent" \
            --output text
